pipeline {
    agent {
        label "terraform-exec"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/bharathkkb/simple-terraform-gcp-example.git'
            }
        }
        stage('TF init & validate') {
            steps {
                 container('terraform') {
                sh '''cd simple-example-destroy
                terraform init
                terraform validate'''
                 }
            }
        }
        stage('TF Destroy Plan') {
            steps {
                 container('terraform') {
                   sh '''cd simple-example-destroy
                terraform plan -destroy -var project_id=$PROJECT_ID'''
                 }
            }
        }
            stage('Wait for Appproval') {
              when { branch "master" }
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Destroy Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Destroy terraform', name: 'confirm'] ])
        }
      }
    }
        stage('TF Destroy') {
          when { branch "master" }
      steps {
        container('terraform') {
          sh '''cd simple-example-destroy
          terraform destroy  -var project_id=test-project-174a -auto-approve'''
        }
      }
    }
    }
}